services:
   adoption-backend:
      extends:
         file: adoption-system-backend/compose.yaml
         service: backend

   adoption-frontend:
      extends:
         file: adoption-system-frontend/compose.yaml
         service: frontend